<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXm7acnk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXm7acnk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXm7acnk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXm7acnk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXm7acnk\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xm7acnk',
    'container.build_id' => 'f50ba469',
    'container.build_time' => 1529772989,
));
